#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{nginx/site-confs,log/nginx,keys,docker-readme-sync} \
	/run \
	/var/lib/nginx/tmp/client_body

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf

[[ ! -f /config/docker-readme-sync/settings.yml ]] && \
	cp /opt/docker-readme-sync/config/settings.yml.example /config/docker-readme-sync/settings.yml

[[ ! -f /config/nginx/site-confs/default ]] && \
	cp /defaults/default /config/nginx/site-confs/default

[[ ! -f /opt/docker-readme-sync/config/settings.yml ]] && \
    ln -s /config/docker-readme-sync/settings.yml /opt/docker-readme-sync/config/settings.yml

# permissions
chown -R abc:abc \
	/config \
	/run \
	/var/lib/nginx
chmod -R g+w \
	/config/{nginx,log,}
